languageCode = "en-uk"
title = "Tom Ward's blog"
pygmentsUseClasses = true
uglyurls = true

[permalinks]
  posts = "/:year/:month/:title/"
  links = "/:year/:month/:slug"

[taxonomies]
  tag = "tags"
